version: '3'

services:
  web:
    build:
      context: .
    command: [
      "python", "manage.py", "runserver", "0.0.0.0:8000"
    ]
    ports:
      - "0.0.0.0:65000:8000"
    entrypoint: [
      "./entrypoint.sh"
    ]
    depends_on:
      - db
    volumes:
      - .:/code/
    environment:
      POSTGRES_PASSWORD: insurance
      POSTGRES_USER: super_user
      POSTGRES_DB: democrance
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    env_file:
      - .env

  db:
    image: postgres:14.4-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: insurance
      POSTGRES_USER: super_user
      POSTGRES_DB: democrance
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
