# Generated by Django 5.0 on 2023-12-19 12:18

import django.utils.timezone
from django.db import migrations, models

import insurance.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('personal_accident', 'PERSONAL_ACCIDENT'), ('heath', 'HEALTH'), ('motor_vehicle', 'MOTOR_VEHICLE')], default=insurance.utils.PolicyTypes['PERSONAL_ACCIDENT'], max_length=40)),
                ('state', models.CharField(choices=[('new', 'NEW'), ('quoted', 'QUOTED'), ('active', 'ACTIVE')], default='new', max_length=40)),
                ('premium', models.PositiveIntegerField(default=0)),
                ('cover', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_state', models.CharField(choices=[('new', 'NEW'), ('quoted', 'QUOTED'), ('active', 'ACTIVE')], default=insurance.utils.PolicyStates['NEW'], max_length=40)),
                ('old_state', models.CharField(choices=[('new', 'NEW'), ('quoted', 'QUOTED'), ('active', 'ACTIVE')], default=insurance.utils.PolicyStates['NEW'], max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
