# Generated by Django 5.0 on 2023-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_alter_policy_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('personal_accident', 'PERSONAL_ACCIDENT'), ('health', 'HEALTH'), ('motor_vehicle', 'MOTOR_VEHICLE')], default='personal_accident', max_length=40),
        ),
    ]
